language: go

env:
  global:
    - secure: "eeNMlx6p5WaPt+GuuO861K9XnftSrb+UtIjmZnqB1ZpsTDFPIQ/3x89PwsjXSLu4uarWoXzX0K/kkNqCfp/G3ObsYfv0WiOBgCOQU1sgaXPWqmgD7LmVvnGaWSKU5TFKguzUFh107cCV5WX+GTjqgi8awrqORmBIabW/GkkxmfU="
    - secure: "TvlsXYLThFmsJTPHr84MYQ+pCmU/yGh8/dftiMCv1SHF2i7JDUFefU3kNr4PUbsbjNjlcWtHQchaYxTKMRN9EfVtkMq/V48rw3634n2OqP/lYsU0UHVFPh2M5wqfts/+A68s2zY49ag+ReZIOKKvKkOg1qqk8f/L5Och4g26y7o="

install:
  - go get github.com/mitchellh/gox

script: ./build.sh

after_success:
  - "find dist -type f | cut -c 6- | xargs -I BUILD_PRODUCT curl --fail -T dist/BUILD_PRODUCT -u$BINTRAY_USER:$BINTRAY_API_KEY https://api.bintray.com/content/$BINTRAY_USER/packer-builder-softlayer/main/$TRAVIS_BUILD_NUMBER.$TRAVIS_BRANCH.$TRAVIS_COMMIT/$TRAVIS_BUILD_NUMBER.$TRAVIS_BRANCH.$TRAVIS_COMMIT/BUILD_PRODUCT"

